 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/new_galleries", type: :request do
  # NewGallery. As you add validations to NewGallery, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      NewGallery.create! valid_attributes
      get new_galleries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      new_gallery = NewGallery.create! valid_attributes
      get new_gallery_url(new_gallery)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_new_gallery_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      new_gallery = NewGallery.create! valid_attributes
      get edit_new_gallery_url(new_gallery)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new NewGallery" do
        expect {
          post new_galleries_url, params: { new_gallery: valid_attributes }
        }.to change(NewGallery, :count).by(1)
      end

      it "redirects to the created new_gallery" do
        post new_galleries_url, params: { new_gallery: valid_attributes }
        expect(response).to redirect_to(new_gallery_url(NewGallery.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new NewGallery" do
        expect {
          post new_galleries_url, params: { new_gallery: invalid_attributes }
        }.to change(NewGallery, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post new_galleries_url, params: { new_gallery: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested new_gallery" do
        new_gallery = NewGallery.create! valid_attributes
        patch new_gallery_url(new_gallery), params: { new_gallery: new_attributes }
        new_gallery.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the new_gallery" do
        new_gallery = NewGallery.create! valid_attributes
        patch new_gallery_url(new_gallery), params: { new_gallery: new_attributes }
        new_gallery.reload
        expect(response).to redirect_to(new_gallery_url(new_gallery))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        new_gallery = NewGallery.create! valid_attributes
        patch new_gallery_url(new_gallery), params: { new_gallery: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested new_gallery" do
      new_gallery = NewGallery.create! valid_attributes
      expect {
        delete new_gallery_url(new_gallery)
      }.to change(NewGallery, :count).by(-1)
    end

    it "redirects to the new_galleries list" do
      new_gallery = NewGallery.create! valid_attributes
      delete new_gallery_url(new_gallery)
      expect(response).to redirect_to(new_galleries_url)
    end
  end
end
